apiVersion: v1
kind: Config
clusters:
- name: "swe645-hw2-cluster"
  cluster:
    server: "https://ec2-54-144-90-120.compute-1.amazonaws.com/k8s/clusters/c-m-txrqw4gp"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      Fk0T0RRNQpNRFE0T0RBZUZ3MHlNekEzTURReE56QTRNRGhhRncwek16QTNNREV4TnpBNE1EaGFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE5qZzRORGt3TkRnNE1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRTJ6OW00MkFEanpzcgpsZmI3Q3RXYmZTMUtPZmxHUnVCZmt3TEFCQ\
      WRWYkZBWVQ2bC9UQ0ozY09rTVBMT2IwL3VJUFFpZW8yL2dVRXhUClNvQi9EUWRiZktOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGS\
      WRrRjZnQVlvTG51ZzczSDVBWGRBemtsRnpoTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFEZAozd\
      kVTSTNFeVg1clVoaVpMdDYxUHdQT283aERiWVlsczFzSTBqQjlXZXdJZ1lrTk9HQUo1c3hmak8xc\
      U0xSmIxCldhTEJoMFkvYzFiTWxtZXk3TldpR3NjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "swe645-hw2-cluster"
  user:
    token: "kubeconfig-user-tv8rwz76q2:mv5d298grjxqbvr2j9c92r9zq8pmc8fvpvsrsktkv66tv7kx2h5v7g"


contexts:
- name: "swe645-hw2-cluster"
  context:
    user: "swe645-hw2-cluster"
    cluster: "swe645-hw2-cluster"

current-context: "swe645-hw2-cluster"
